/**
 * lib.mjs — docs-gen 各模块共享的提取/输出辅助层
 *
 * 被 scripts/docs-gen.mjs 入口分发的各模块生成器（damage-calculator.mjs / relic-free.mjs）共用。
 * 约束：纯 Node（>=20）、零依赖、输出确定性（不写时间戳）。
 *
 * 提取规则（全部生成器共同遵守）：
 * - 行首（去除缩进后）以 // 开头的行视为注释，其中的注册调用/名单条目不计入；
 * - 括号/中括号配对扫描会跳过字符串字面量与块注释，名单条目中含 [ ] 的 key 不会破坏配对。
 */

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// ---------------------------------------------------------------------------
// 路径
// ---------------------------------------------------------------------------

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

export const AUTO_BANNER = "<!-- AUTO-GENERATED by scripts/docs-gen.mjs — 勿手改，运行 yarn docs:gen 重新生成 -->";

export function read(rel) {
  return readFileSync(path.join(ROOT, rel), "utf8");
}

/** 确定性排序（按 UTF-16 码元，不依赖 locale/ICU） */
export function cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

// ---------------------------------------------------------------------------
// 通用提取工具
// ---------------------------------------------------------------------------

/**
 * 把一行拆成 [代码部分, 行尾 // 注释文本]。
 * 扫描时跳过字符串字面量，字符串内的 // 不会被误判为注释。
 */
export function splitCodeAndComment(line) {
  let inStr = null;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inStr) {
      if (ch === "\\") i++;
      else if (ch === inStr) inStr = null;
    } else if (ch === '"' || ch === "'" || ch === "`") {
      inStr = ch;
    } else if (ch === "/" && line[i + 1] === "/") {
      return [line.slice(0, i), line.slice(i + 2).trim()];
    }
  }
  return [line, ""];
}

/**
 * 从 startIdx（须指向 openChar）开始做括号配对，返回与之配对的 closeChar 下标。
 * 跳过字符串字面量、行注释、块注释；不配对返回 -1。
 */
export function findBalancedEnd(src, startIdx, openChar, closeChar) {
  let depth = 0;
  let inStr = null;
  let inLine = false;
  let inBlock = false;
  for (let i = startIdx; i < src.length; i++) {
    const ch = src[i];
    const next = src[i + 1];
    if (inLine) {
      if (ch === "\n") inLine = false;
      continue;
    }
    if (inBlock) {
      if (ch === "*" && next === "/") {
        inBlock = false;
        i++;
      }
      continue;
    }
    if (inStr) {
      if (ch === "\\") i++;
      else if (ch === inStr) inStr = null;
      continue;
    }
    if (ch === "/" && next === "/") {
      inLine = true;
      i++;
      continue;
    }
    if (ch === "/" && next === "*") {
      inBlock = true;
      i++;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      inStr = ch;
      continue;
    }
    if (ch === openChar) depth++;
    else if (ch === closeChar) {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

/**
 * 从 anchorRe 命中处开始做括号配对，返回 openChar..closeChar 之间的内容（不含两端括号）。
 * 跳过字符串字面量、行注释、块注释，因此 "atk_up[life_point]" 这类 key 不会破坏配对。
 */
export function extractBalancedBlock(src, anchorRe, openChar, closeChar, what) {
  const m = src.match(anchorRe);
  if (!m) throw new Error(`提取失败：未找到 ${what}（anchor: ${anchorRe}）`);
  const start = src.indexOf(openChar, m.index + m[0].length);
  if (start === -1) throw new Error(`提取失败：${what} 缺少起始 ${openChar}`);
  const end = findBalancedEnd(src, start, openChar, closeChar);
  if (end === -1) throw new Error(`提取失败：${what} 括号不配对`);
  return src.slice(start + 1, end);
}

/** 解析字符串数组字面量主体：字符串条目 + 箭头函数动态条目；统计被注释掉的条目数 */
export function parseArrayEntries(block) {
  const entries = [];
  let commentedOut = 0;
  for (const rawLine of block.split("\n")) {
    const trimmed = rawLine.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("//")) {
      if (/^\/\/\s*["'`(]/.test(trimmed)) commentedOut++;
      continue;
    }
    const [code, comment] = splitCodeAndComment(rawLine);
    const strs = [...code.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((s) => s[1]);
    if (strs.length === 0 && code.includes("=>")) {
      // 动态条目，如 (charData) => `damage_scale[${charData.profession.toLowerCase()}]`
      const tpl = code.match(/`([^`]+)`/);
      entries.push({ value: tpl ? tpl[1] : code.trim(), dynamic: true, comment });
      continue;
    }
    strs.forEach((s, idx) => {
      entries.push({ value: s, dynamic: false, comment: idx === strs.length - 1 ? comment : "" });
    });
  }
  return { entries, commentedOut };
}

/** 解析 Record<string,string> 对象字面量主体（key: "中文", // 行尾注释） */
export function parseObjectEntries(block) {
  const entries = [];
  for (const rawLine of block.split("\n")) {
    const trimmed = rawLine.trim();
    if (!trimmed || trimmed.startsWith("//")) continue;
    const [code, comment] = splitCodeAndComment(rawLine);
    const m = code.match(/^\s*(?:"([^"]+)"|([A-Za-z_$][\w$]*))\s*:\s*"([^"]*)"\s*,?\s*$/);
    if (m) entries.push({ key: m[1] ?? m[2], value: m[3], comment });
  }
  return entries;
}

/**
 * parseObjectEntries 的扩展版：
 * - 键支持 "字符串" / Unicode 标识符（含中文键，如 深池方阵步兵）/ 计算键 [Enum.MEMBER]；
 * - 值支持 "字符串" 与数值字面量。
 * 计算键返回 { computedKey: "Enum.MEMBER" }，由调用方按枚举表解析。
 */
export function parseObjectEntriesExt(block) {
  const entries = [];
  const re =
    /^\s*(?:"([^"]+)"|\[([\w$.]+)\]|([\p{ID_Start}$_][\p{ID_Continue}$]*))\s*:\s*(?:"([^"]*)"|(-?\d+(?:\.\d+)?))\s*,?\s*$/u;
  for (const rawLine of block.split("\n")) {
    const trimmed = rawLine.trim();
    if (!trimmed || trimmed.startsWith("//")) continue;
    const [code, comment] = splitCodeAndComment(rawLine);
    const m = code.match(re);
    if (!m) continue;
    entries.push({
      key: m[1] ?? m[3] ?? null,
      computedKey: m[2] ?? null,
      value: m[4] !== undefined ? m[4] : Number(m[5]),
      numeric: m[5] !== undefined,
      comment,
    });
  }
  return entries;
}

/** 取某行上方紧邻的单行 JSDoc 注释（/** ... *​/），无则返回空串 */
export function docCommentAbove(lines, idx) {
  for (let j = idx - 1; j >= 0; j--) {
    const t = lines[j].trim();
    if (!t) continue;
    let m = t.match(/^\/\*\*\s*(.*?)\s*\*\/$/);
    if (m) return m[1];
    m = t.match(/^\/\/\s*\/\*\*\s*(.*?)\s*\*\/$/); // 被整段注释掉时的形态：// /** ... */
    if (m) return m[1];
    return "";
  }
  return "";
}

/** 递归收集 absDir 下扩展名匹配的文件（相对路径，正斜杠，目录/文件名按 cmp 排序保证确定性） */
export function walkFiles(absDir, exts, relPrefix = "") {
  const files = [];
  const ents = readdirSync(absDir, { withFileTypes: true }).sort((a, b) => cmp(a.name, b.name));
  for (const ent of ents) {
    if (ent.isDirectory()) files.push(...walkFiles(path.join(absDir, ent.name), exts, `${relPrefix}${ent.name}/`));
    else if (exts.some((ext) => ent.name.endsWith(ext))) files.push(`${relPrefix}${ent.name}`);
  }
  return files;
}

// ---------------------------------------------------------------------------
// Markdown 输出工具
// ---------------------------------------------------------------------------

export function mdCell(text) {
  const t = String(text ?? "").replaceAll("|", "\\|").replaceAll("\n", " ").trim();
  return t === "" ? "—" : t;
}

export function mdTable(headers, rows) {
  const out = [];
  out.push(`| ${headers.join(" | ")} |`);
  out.push(`|${headers.map(() => "---").join("|")}|`);
  for (const row of rows) out.push(`| ${row.map(mdCell).join(" | ")} |`);
  return out.join("\n");
}

export function docHeader(sources) {
  return [AUTO_BANNER, "---", "generated: true", "sources:", ...sources.map((s) => `  - ${s}`), "---", ""].join("\n");
}

export function writeDoc(outDir, filename, content) {
  mkdirSync(outDir, { recursive: true });
  const abs = path.join(outDir, filename);
  writeFileSync(abs, content.endsWith("\n") ? content : content + "\n");
  return abs;
}
